# fly.toml file generated for guiapp on 2022-06-03T02:51:17+08:00

app = "appweb"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
#  LOG_LEVEL = "debug"

[build]
  dockerfile = "Dockerfile"
# image = "arshcs/appweb:latest"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
port = 9091 # default for most prometheus clients
path = "/metrics" # default for most prometheus clients

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  http_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "5s"
    restart_limit = 0
    timeout = "2s"
